spring:
  application:
    name: otboo
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        #        highlight_sql: true
        #        use_sql_comments: true
        format_sql: true
    open-in-view: false
  batch:
    job:
      enabled: false

otboo:
  admin:
    name: ${ADMIN_NAME:admin}
    email: ${ADMIN_EMAIL:admin@admin.com}
    password: ${ADMIN_PASSWORD:admin1234}
  file:
    storage:
      type: ${FILE_STORAGE_TYPE:local}
      path: ${FILE_STORAGE_PATH:${user.dir}/fileStorage}


# ?? ?? ??
logging:
  level:
    root: info
#    org.hibernate.SQL: debug // p6spy로 대신 로깅

# ?????
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers
  info:
    env:
      enabled: true
