spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_ADDR}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_KEY}" password="${KAFKA_SECRET}";
    consumer:
      group-id: prod-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

otboo:
  admin:
    name: ${ADMIN_NAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  file:
    storage:
      type: s3

jwt:
  secret: ${JWT_SECRET}