spring:
  application:
    name: otboo
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

otboo:
  admin:
    name: ${ADMIN_NAME:admin}
    email: ${ADMIN_EMAIL:admin@admin.com}
    password: ${ADMIN_PASSWORD:admin1234}

# ?? ?? ??
logging:
  level:
    root: info
    org.hibernate.SQL: debug

# ?????
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers
  info:
    env:
      enabled: true
